from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from html import escape
from pathlib import Path


@dataclass(frozen=True)
class PageSection:
    title: str
    body: str


DEFAULT_SECTIONS = [
    PageSection(
        "What This Project Does",
        "This page was generated by a Python script and published from a GitHub repository.",
    ),
    PageSection(
        "Why It Is Useful",
        "Python can create repeatable website output, which is useful for reports, dashboards, notes, and project pages.",
    ),
    PageSection(
        "Next Step",
        "Edit the Python generator, run it again, commit the changed HTML, and push to GitHub.",
    ),
]


def build_html(
    title: str = "Python Generated Web Page",
    subtitle: str = "Generated locally with Python and ready for GitHub Pages.",
    sections: list[PageSection] | None = None,
) -> str:
    page_sections = sections or DEFAULT_SECTIONS
    section_markup = "\n".join(
        f"""        <article class="card">
          <h2>{escape(section.title)}</h2>
          <p>{escape(section.body)}</p>
        </article>"""
        for section in page_sections
    )

    today = date.today().isoformat()
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{escape(title)}</title>
  <style>
    :root {{
      --bg: #f4f7fb;
      --ink: #172033;
      --muted: #5f6f89;
      --panel: #ffffff;
      --line: #d9e2ef;
      --blue: #2563eb;
      --green: #17803d;
    }}

    * {{
      box-sizing: border-box;
    }}

    body {{
      margin: 0;
      font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Arial, sans-serif;
      background: var(--bg);
      color: var(--ink);
      line-height: 1.65;
    }}

    header {{
      background: linear-gradient(135deg, #0f172a, #1d4ed8);
      color: white;
      padding: 56px 20px;
    }}

    .wrap {{
      width: min(960px, calc(100% - 32px));
      margin: 0 auto;
    }}

    h1 {{
      margin: 0;
      font-size: clamp(2rem, 7vw, 4rem);
      line-height: 1.05;
    }}

    .subtitle {{
      max-width: 720px;
      margin: 14px 0 0;
      color: #dbeafe;
      font-size: 1.1rem;
    }}

    main {{
      padding: 28px 0 48px;
    }}

    .grid {{
      display: grid;
      grid-template-columns: repeat(3, minmax(0, 1fr));
      gap: 16px;
    }}

    .card {{
      background: var(--panel);
      border: 1px solid var(--line);
      border-radius: 8px;
      padding: 20px;
      box-shadow: 0 14px 34px rgba(15, 23, 42, .08);
    }}

    .card h2 {{
      margin: 0 0 8px;
      font-size: 1.2rem;
    }}

    .card p {{
      margin: 0;
      color: var(--muted);
    }}

    .note {{
      margin-top: 18px;
      border-left: 5px solid var(--green);
      background: #ecfdf3;
      border-radius: 8px;
      padding: 14px 16px;
      font-weight: 700;
    }}

    footer {{
      color: var(--muted);
      padding: 0 0 36px;
      text-align: center;
    }}

    @media (max-width: 760px) {{
      .grid {{
        grid-template-columns: 1fr;
      }}
    }}
  </style>
</head>
<body>
  <header>
    <div class="wrap">
      <h1>{escape(title)}</h1>
      <p class="subtitle">{escape(subtitle)}</p>
    </div>
  </header>

  <main class="wrap">
    <section class="grid">
{section_markup}
    </section>

    <div class="note">Generated on {today} by <code>repo_python</code>.</div>
  </main>

  <footer class="wrap">
    Published from GitHub using a Python-generated HTML file.
  </footer>
</body>
</html>
"""


def write_html(output_path: str | Path) -> Path:
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(build_html(), encoding="utf-8")
    return path
